### ISSUE TITLE
gp3 support from aws provider 3.25+

### ISSUE THREAD

**Issue by jgilfoil** [terraform-aws-modules/.github#19]
## Is your request related to a new offering from AWS?
yes! gp3 support is available in provider 3.25 and later.

## Is your request related to a problem? Please describe.
I'd like to be able to enable gp3 volume type for the root_block_device (or any volume) on instances.

## Describe the solution you'd like.
Ideally, updating the supported provider version to support gp3. However, I recognize updating to provider versions is a big deal, but is there any possibility of this happening in the future or should I move on to another module for the time being?

## Describe alternatives you've considered.
Using other modules is all I could really think of here.

## Additional context
```
module.ec2.aws_instance.this[0]: Refreshing state... [id=i-081a00cce42c2fa77]

Error: expected root_block_device.0.volume_type to be one of [standard io1 gp2 sc1 st1], got gp3
```

**Comment by bryantbiggs** [comment]
checkout the latest at https://github.com/terraform-aws-modules/terraform-aws-ec2-instance, this should be available already 

@antonbabenko we can close this 👍🏽
